import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import useSWR from "swr";
import { get, post } from "../libs/fetcher";
import styles from "../styles/Home.module.css";
import { Howl, Howler } from "howler";
// import mp3 from "../demo/shit.mp3";
import {
  map,
  T,
  F,
  prop,
  o,
  ifElse,
  over,
  lensProp,
  set,
  find,
  propEq,
  isNil,
} from "ramda";
import Player from "../components/Player";
import PlayList, { PlayListData } from "../components/PlayList";

function blobToArrayBuffer(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.addEventListener("loadend", (e) => {
      resolve(reader.result);
    });
    reader.addEventListener("error", reject);
    reader.readAsArrayBuffer(blob);
  });
}

let mapList = (item) =>
  map((it) => {
    return over(lensProp("isPlaying"), it === item ? T : F, it);
  });

export default function Home() {
  const { data: filesList } = useSWR("/api/getFiles");
  const [playList, setPlayList] = useState<PlayListData>([]);
  const [showPlayList, setShowPlayList] = useState(false);

  const playingItem = find(propEq("isPlaying", true), playList);
  const isPlaying = !isNil(playingItem);

  console.log(isPlaying);

  const clickItemHandler = (item) => {
    // if (item === )
    setPlayList(mapList(item));
  };

  useEffect(() => {
    if (!filesList) {
      return;
    }

    setPlayList(
      filesList.files.map((item) => ({
        isPlaying: false,
        id: item.id,
        name: item.name,
        src: item["@microsoft.graph.downloadUrl"],
      }))
    );
  }, [filesList]);

  useEffect(() => {
    if (!playingItem) {
      return;
    }

    let howl;

    get(playingItem.src, {
      responseType: "arraybuffer",
      onDownloadProgress: (progressEvent) => {
        console.log(progressEvent);
      },
    }).then((res: any) => {
      const blob = new Blob([res.data], { type: "audio/mpeg" });
      const audioUrl = URL.createObjectURL(blob);
      howl = new Howl({
        src: [audioUrl],
        format: ["mp3"],
        onload: (...args) => {},
      });
      howl?.play();
    });

    return () => {
      howl?.stop();
    };
  }, [playingItem]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full">
        <Player
          isPlaying={isPlaying}
          currentTime={0}
          totalTime={0}
          musicTitle={""}
          onPause={() => {}}
          onPlay={() => {}}
        ></Player>
        <PlayList
          playListData={playList}
          onClickItem={clickItemHandler}
        ></PlayList>
      </main>
    </>
  );
}
